export enum WarningMsg {
  isUserExist = "Your record exists in our system, kindly login",
  userNotExist = "User does not exist",
  isUserExistWithoutPhoneNo = "Your record exist in our system but your mobile does not match, would you like to add this number?",
  otpNotMatched = "Your OTP does not match",
  emailNotMatched = "Please enter registered email address",
  maxAttempts = "Maximum attempts has been reached",
  emailNotGiven = "Your account is not registered with an email address",
  accountNotRegisterd = "Your account is not registered",
  securityAnswersNotMatched = "Security answers are not correct",
  emailVerification = "Verification link is sent to your email",
  failedEmailVerification = "Invalid email",
  profileNotComplete="Your profile is not complete",
  otpFailure="Unable to sent otp",
  otpSent = "Otp is sent to your email",
  invalidOptions = "Option is not valid",
  emailNotExist = "Email not exist",
  securityQusNotExist = "Security question not exist",
  userAlreadyExsist ="User already exist"
}
